import { StyleSheet } from 'react-native';

export const colors = {
  accent: '#087E5B',
  background: '#F3F5F7',
  border: '#D7DDE2',
  muted: '#66727D',
  surface: '#FFFFFF',
  text: '#17212B',
} as const;

export const testStyles = StyleSheet.create({
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  colorButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 6,
    borderWidth: 2,
    height: 36,
    justifyContent: 'center',
    width: 52,
  },
  colorSelected: { borderColor: colors.text },
  content: {
    gap: 22,
    paddingBottom: 40,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  field: { gap: 6 },
  fieldLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  input: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 6,
    borderWidth: 1,
    color: colors.text,
    height: 42,
    paddingHorizontal: 12,
  },
  modeButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 5,
    borderWidth: 1,
    flexBasis: '30%',
    flexGrow: 1,
    height: 36,
    justifyContent: 'center',
  },
  modeSelected: { backgroundColor: colors.text, borderColor: colors.text },
  modeText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  modeTextSelected: { color: colors.surface },
  popup: { gap: 16, padding: 20 },
  popupFullscreen: { flex: 1, justifyContent: 'center' },
  popupMeta: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  popupTitle: { color: colors.text, fontSize: 19, fontWeight: '700' },
  progressTrack: {
    backgroundColor: colors.border,
    height: 5,
    overflow: 'hidden',
  },
  progressValue: {
    backgroundColor: colors.accent,
    height: '100%',
    transformOrigin: 'left',
    width: '100%',
  },
  screen: { backgroundColor: colors.background, flex: 1 },
  section: { gap: 12 },
  sectionHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionMeta: { color: colors.muted, fontSize: 11 },
  sectionTitle: { color: colors.text, fontSize: 16, fontWeight: '700' },
  status: {
    backgroundColor: '#E8F3EF',
    borderLeftColor: colors.accent,
    borderLeftWidth: 3,
    color: colors.text,
    fontSize: 12,
    lineHeight: 18,
    padding: 10,
  },
  switchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  switchText: { color: colors.text, fontSize: 14 },
});
