export const DEFAULT_POPUP_APPEARANCE = {
  maskColor: 'rgba(0, 0, 0, 0.46)',
  popupBackgroundColor: '#ffffff',
  popupRadius: 8,
  toastBackgroundColor: 'rgba(24, 24, 24, 0.92)',
  toastTextColor: '#ffffff',
  toastRadius: 7,
  modalBackgroundColor: '#ffffff',
  modalTextColor: '#111111',
  modalSecondaryTextColor: '#5d5d5d',
  modalSeparatorColor: '#dedede',
  modalInputBackgroundColor: '#f2f2f2',
  modalRadius: 8,
  confirmColor: '#576b95',
  cancelColor: '#000000',
} as const;
