import { StyleSheet } from 'react-native';

export const popupComponentsStyles = StyleSheet.create({
  action: {
    alignItems: 'center',
    borderColor: '#D7DDE2',
    borderRadius: 6,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  actionPrimary: { backgroundColor: '#087E5B', borderColor: '#087E5B' },
  actionText: { color: '#17212B', fontSize: 13, fontWeight: '600' },
  actionTextPrimary: { color: '#FFFFFF' },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  content: { gap: 20, padding: 16, paddingBottom: 48 },
  customModal: {
    backgroundColor: '#FFF1D6',
    borderColor: '#087E5B',
    borderRadius: 6,
    borderWidth: 2,
    gap: 14,
    minWidth: 280,
    padding: 20,
  },
  customModalTitle: { color: '#087E5B', fontSize: 18, fontWeight: '800' },
  footer: { flexDirection: 'row', gap: 8, padding: 16, paddingTop: 0 },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D7DDE2',
    borderRadius: 6,
    borderWidth: 1,
    color: '#17212B',
    height: 42,
    paddingHorizontal: 12,
  },
  localContent: { gap: 12 },
  screen: { backgroundColor: '#F3F5F7', flex: 1 },
  section: { gap: 10 },
  status: {
    backgroundColor: '#E8F3EF',
    borderLeftColor: '#087E5B',
    borderLeftWidth: 3,
    color: '#17212B',
    fontSize: 12,
    lineHeight: 18,
    padding: 10,
  },
  title: { color: '#17212B', fontSize: 16, fontWeight: '700' },
});
