import { StyleSheet } from 'react-native';

import { DEFAULT_POPUP_APPEARANCE } from './defaults';

export const styles = StyleSheet.create({
  globalHost: { flex: 1, position: 'relative' },
  localHost: { position: 'relative' },
  nativeHost: { flex: 1 },
  layer: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  mask: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  placement: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  popup: {
    backgroundColor: DEFAULT_POPUP_APPEARANCE.popupBackgroundColor,
    borderCurve: 'continuous',
    borderRadius: DEFAULT_POPUP_APPEARANCE.popupRadius,
    boxShadow: '0 8px 28px rgba(0, 0, 0, 0.18)',
    maxWidth: 360,
    overflow: 'hidden',
  },
  fullscreenPopup: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    boxShadow: 'none',
    height: '100%',
    maxWidth: '100%',
    width: '100%',
  },
  toast: {
    alignItems: 'center',
    backgroundColor: DEFAULT_POPUP_APPEARANCE.toastBackgroundColor,
    borderCurve: 'continuous',
    borderRadius: DEFAULT_POPUP_APPEARANCE.toastRadius,
    gap: 12,
    justifyContent: 'center',
    minHeight: 118,
    paddingHorizontal: 18,
    paddingVertical: 18,
    width: 132,
  },
  toastWithoutIcon: {
    maxWidth: 280,
    minHeight: 44,
    paddingVertical: 12,
    width: 'auto',
  },
  toastIcon: {
    color: DEFAULT_POPUP_APPEARANCE.toastTextColor,
    fontSize: 42,
    fontWeight: '400',
    lineHeight: 48,
  },
  toastImage: { height: 44, width: 44 },
  toastText: {
    color: DEFAULT_POPUP_APPEARANCE.toastTextColor,
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'center',
  },
  modal: {
    backgroundColor: DEFAULT_POPUP_APPEARANCE.modalBackgroundColor,
    borderCurve: 'continuous',
    borderRadius: DEFAULT_POPUP_APPEARANCE.modalRadius,
    boxShadow: '0 10px 34px rgba(0, 0, 0, 0.2)',
    maxWidth: 340,
    overflow: 'hidden',
    width: '88%',
  },
  modalBody: { alignItems: 'stretch', gap: 12, padding: 22 },
  modalTitle: {
    color: DEFAULT_POPUP_APPEARANCE.modalTextColor,
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalContent: {
    color: DEFAULT_POPUP_APPEARANCE.modalSecondaryTextColor,
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: DEFAULT_POPUP_APPEARANCE.modalInputBackgroundColor,
    borderRadius: 5,
    color: DEFAULT_POPUP_APPEARANCE.modalTextColor,
    fontSize: 15,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  modalActions: {
    borderTopColor: DEFAULT_POPUP_APPEARANCE.modalSeparatorColor,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
  },
  modalButton: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 10,
  },
  modalCancelButton: {
    borderRightColor: DEFAULT_POPUP_APPEARANCE.modalSeparatorColor,
    borderRightWidth: StyleSheet.hairlineWidth,
  },
  modalButtonText: { fontSize: 16, fontWeight: '500' },
});
